const asset = (path) => `${import.meta.env.BASE_URL}${path}`;
const photo = (file) => asset(`media/photo/${file}`);

export const content = {
  video: {
    src: asset("media/main-video.mp4"),
    poster: "",
  },
  tabs: ["精选", "关注", "推荐"],
  activeTab: "推荐",
  profile: {
    name: "都市爆料君",
    avatar: asset("media/avatar-urban-news.png"),
  },
  description: {
    text: "美术室惊现恶性一幕！裸模因不满老师点评突然出手，拳拳到脸现场失控...",
    tags: ["美术生", "社会百态", "正能量"],
  },
  counts: {
    like: 326000,
    comment: 41000,
    favorite: 12000,
    share: 87000,
  },
  searchTopic: "一只鱼儿",
  danmaku: {
    defaultDuration: 6,
    items: [
      { text: "这个模特有力气", at: 0.4, track: 0, duration: 6.2 },
      { text: "这一下全班都醒了", at: 0.9, track: 2, duration: 6.1 },
      { text: "看着不像摆拍啊", at: 1.4, track: 1, duration: 6 },
      { text: "老师也太惨了吧", at: 2.0, track: 3, duration: 6.5 },
      { text: "警察：不想上班", at: 2.6, track: 0, duration: 6.1 },
      { text: "管他谁的问题，看乐子就对了", at: 3.2, track: 2, duration: 6.4 },
      { text: "有点像那个卖鱼的博主", at: 3.9, track: 1, duration: 6.7 },
      { text: "这一拳挨得结结实实", at: 4.5, track: 3, duration: 6 },
      { text: "吃瓜群众集合", at: 5.1, track: 0, duration: 6.2 },
      { text: "刚进来，谁打谁", at: 5.7, track: 2, duration: 6 },
      { text: "美术生上课都这么刺激吗", at: 6.3, track: 1, duration: 6.5 },
      { text: "先别站队，等后续", at: 6.9, track: 3, duration: 6.1 },
      { text: "楼上说的卖鱼那个我懂了", at: 7.5, track: 0, duration: 6.7 },
      { text: "这一拳老师要懵半天", at: 8.1, track: 2, duration: 6.2 },
      { text: "老师点评太直白也不能动手吧", at: 8.8, track: 1, duration: 6.3 },
      { text: "蹲一个后续", at: 9.5, track: 3, duration: 6 },
      { text: "现场肯定乱成一锅了", at: 10.2, track: 0, duration: 6.4 },
      { text: "评论区比视频还精彩", at: 10.9, track: 2, duration: 6.1 },
      { text: "我也觉得很像那个卖鱼的", at: 11.6, track: 1, duration: 6.8 },
      { text: "旁边同学手真稳", at: 12.2, track: 3, duration: 6.2 },
      { text: "这一拳谁看了不愣一下", at: 12.9, track: 0, duration: 6.4 },
      { text: "美术老师也是高危职业了", at: 13.6, track: 2, duration: 6.5 },
      { text: "标题一股自媒体味", at: 14.4, track: 1, duration: 6.1 },
      { text: "吃瓜归吃瓜，别网暴", at: 15.1, track: 3, duration: 6.3 },
      { text: "前排卖瓜子", at: 15.8, track: 0, duration: 6 },
      { text: "老师那句点评到底说了啥", at: 16.5, track: 2, duration: 6.2 },
      { text: "这不是课堂，这是新闻现场", at: 17.2, track: 1, duration: 6.5 },
      { text: "别光看热闹，动手肯定不对", at: 17.9, track: 3, duration: 6.6 },
      { text: "后续呢后续呢", at: 18.6, track: 0, duration: 6.1 },
      { text: "弹幕又刷怪了", at: 19.3, track: 2, duration: 6.4 },
      { text: "警察：不想上班", at: 20.0, track: 1, duration: 6 },
      { text: "这老师今天倒霉了", at: 20.7, track: 3, duration: 6.2 },
      { text: "评论区已经开庭", at: 21.4, track: 0, duration: 6.1 },
      { text: "谁懂，真的有点像", at: 22.1, track: 2, duration: 6.3 },
      { text: "画室直接变案发现场", at: 22.8, track: 1, duration: 6.4 },
      { text: "我只想知道后续", at: 23.5, track: 3, duration: 6.1 },
      { text: "旁边人全在拍", at: 24.2, track: 0, duration: 6 },
      { text: "这要赔医药费吧", at: 24.9, track: 2, duration: 6.2 },
      { text: "别说，还真像", at: 25.6, track: 1, duration: 6.1 },
      { text: "美术生沉默了", at: 26.3, track: 3, duration: 6 },
      { text: "这波太突然", at: 27.0, track: 0, duration: 6.1 },
      { text: "一拳干上热搜", at: 27.7, track: 2, duration: 6.2 },
      { text: "下课铃都不用响了", at: 28.4, track: 1, duration: 6.1 },
      { text: "吃瓜吃到画室来了", at: 29.1, track: 3, duration: 6 },
    ],
  },
  comments: [
    {
      avatar: photo("1.jpg"),
      name: "互联网乐子人",
      text: "这一下全班都醒了",
      time: "05-16",
      likes: 3868,
      replyHint: "展开23条回复",
    },
    {
      avatar: photo("2.jpg"),
      name: "红鲤鱼与绿鲤鱼与驴",
      text: "警察：不想上班",
      time: "05-16",
      likes: 3421,
      replyHint: "展开18条回复",
    },
    {
      avatar: photo("3.png"),
      name: "问就是你对",
      text: "评论区又开始破案了",
      time: "05-16",
      likes: 3197,
      replyHint: "展开31条回复",
    },
    {
      avatar: photo("4.jpg"),
      name: "吃瓜现场一线记者",
      text: "感觉有点像那个卖鱼博主",
      time: "05-16",
      likes: 2876,
      replyHint: "展开12条回复",
    },
    {
      avatar: photo("5.jpg"),
      name: "上善若水",
      text: "楼上的，我也举得有点像",
      time: "05-16",
      likes: 2410,
      replyHint: "展开47条回复",
    },
    {
      avatar: photo("6.jpg"),
      name: "东哥",
      text: "打得好！我也想一拳打我老师身上",
      time: "05-16",
      likes: 2219,
      replyHint: "展开29条回复",
    },
    {
      avatar: photo("7.jpg"),
      name: "暴富小仙女",
      text: "这个模特怎么没啥职业道德，还敢动手打人",
      time: "05-16",
      likes: 1984,
      replyHint: "展开16条回复",
    },
    {
      avatar: photo("8.jpg"),
      name: "杨经理聊房产",
      text: "蹲后续",
      time: "05-16",
      likes: 1726,
      replyHint: "展开9条回复",
    },
    {
      avatar: photo("9.jpg"),
      name: "逐风",
      text: "这个模特有力气",
      time: "05-16",
      likes: 1495,
      replyHint: "展开14条回复",
    },
    {
      avatar: photo("10.jpg"),
      name: "x光x",
      text: "吃瓜吃到自己学校",
      time: "05-16",
      likes: 1288,
      replyHint: "展开36条回复",
    },
    {
      avatar: photo("11.jpg"),
      name: "Randy",
      text: "这裸模身材还行",
      time: "05-16",
      likes: 1042,
      replyHint: "展开7条回复",
    },
    {
      avatar: photo("12.jpg"),
      name: "天津亮少",
      text: "标题一看就是自媒体味儿，但我承认我还是点进来了。",
      time: "05-16",
      likes: 826,
      replyHint: "展开5条回复",
    },
    {
      avatar: photo("13.jpg"),
      name: "用户293847882",
      text: "美术生表示课堂气氛确实会很直接，但动手这一下彻底越界了。",
      time: "05-16",
      likes: 641,
      replyHint: "展开4条回复",
    },
    {
      avatar: photo("14.jpg"),
      name: "爱吃面包",
      text: "同蹲后续",
      time: "05-16",
      likes: 498,
      replyHint: "展开6条回复",
    },
    {
      avatar: photo("15.jpg"),
      name: "小雨曦呀",
      text: "这事最离谱的是旁边同学第一反应居然都在拍。",
      time: "05-16",
      likes: 352,
      replyHint: "展开3条回复",
    },
    {
      avatar: photo("16.jpg"),
      name: "慢为",
      text: "评论区比视频精彩",
      time: "05-16",
      likes: 237,
      replyHint: "展开2条回复",
    },
    {
      avatar: photo("17.jpg"),
      name: "做自己",
      text: "IP 广东，已经有人在群里传了，说是调解了，但不知道真假。",
      time: "05-16",
      likes: 164,
      replyHint: "展开2条回复",
    },
    {
      avatar: photo("18.jpg"),
      name: "CAA",
      text: "吃瓜可以，别去扒人家私生活，视频里这点信息根本不够判断。",
      time: "05-16",
      likes: 96,
      replyHint: "",
    },
    {
      avatar: photo("19.jpg"),
      name: "用户278592838",
      text: "这个封面黄字红底一出来，我就知道评论区肯定比视频精彩。",
      time: "05-16",
      likes: 41,
      replyHint: "",
    },
    {
      avatar: photo("20.jpg"),
      name: "川子",
      text: "老师一句点评能不能说清楚点，别只放打人的几秒。",
      time: "05-16",
      likes: 18,
      replyHint: "",
    },
  ],
  bottomNav: [
    { label: "首页", active: true },
    { label: "朋友" },
    { label: "+" },
    { label: "消息", badge: 6 },
    { label: "我" },
  ],
};
